latitudesite/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^home/',include('login.urls',namespace = "login")),
    url(r'^admin/', admin.site.urls),
]

login/urls.py
from django.conf.urls import url,include

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^login/success',views.success,name= 'success'),
    url(r'^login/register',views.register,name= 'register'),
    url(r'^login/viewdata',views.all_data,name= 'viewdata'),

]

login/models.py
from django.db import models
import os,datetime

# Create your models here.
class LoginData(models.Model):
    """docstring for ."""
    reg_no    = models.AutoField(primary_key=True)
    name      = models.CharField(max_length=50)
    phone_no  = models.IntegerField()
    email     = models.EmailField(max_length = 70)
    id_card   = models.FileField(null=True,blank=True)
    reg_type  = models.CharField(max_length=10)
    no_of_tkt = models.IntegerField()
    reg_date  = models.DateField(default=datetime.date.today)

    def __unicode__(self):
        return self.title

login/forms.py
from django import forms
from .models import LoginData

class LoginForm(forms.ModelForm):
    """docstring for ."""
    class Meta:
        model   = LoginData
        exclude = ('reg_no','reg_date')

login/views.py
from django.shortcuts import render,redirect,HttpResponseRedirect,render_to_response
from django.http import HttpResponse
from .forms import LoginForm
from django.contrib import messages
from django.template import RequestContext
from .models import LoginData

# Create your views here.
# def Home(request):

def index(request):
    return render(request,"login/index.html")

def success(request):
    return render(request,"login/success.html")


def register(request):
    if request.method == 'POST':
        form = LoginForm(request.POST,request.FILES)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.save()
            messages.add_message(request, messages.INFO, 'Your Registrtion completed succesffully, Your id is-' + str(instance.pk))
            return HttpResponseRedirect('success')
    else:
        form = LoginForm()
    context = {
        "form":form,
    }
    return render(request,"login/register.html",context)


def all_data(request):
     queryset = LoginData.objects.all()
     context = {
        "o_list" : queryset,
        "title": "List"
     }
     return render(request,"login/viewReg.html",context)

login/templates/login/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Maa Events</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>

    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

    {% load static %}

    <link rel="stylesheet" type="text/css" href="{% static 'login/style.css' %}" />

  </head>

  <body class="container">
    <h1 class="jumbotron">Welcome to Maa Events</h1>
    <div class="text-center">
      <a class="btn btn-primary" href = "{% url 'login:register' %}">Register</a>
      <a class="btn btn-primary" href = "{% url 'login:viewdata' %}">Admin Login</a>
    </div>
  </body>
</html>

login/templates/login/register.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Registration</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>

    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <!--Selecter dropdown -->
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.1/css/bootstrap-select.min.css">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.1/js/bootstrap-select.min.js"></script>

    <!-- (Optional) Latest compiled and minified JavaScript translation files -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.1/js/i18n/defaults-*.min.js"></script>

    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    {% load static %}
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'login/style.css' %}" />
  </head>
  <body class="container">
  <h1 id = "reg" class="well">Event Registration</h1>
  <h5 class ="alert alert-danger" >All the Fields are mandatory</h5>
  <!-- <form>
    <div class="form-group">
      <label for="name">Full Name:</label>
      <input type="text" class="form-control" id="name" required="true">
    </div>
    <div class="form-group">
      <label for="mob">Mobile:</label>
      <input type="phone" class="form-control" id="mob" required="true" maxlength="10">
    </div>
    <div class="form-group">
      <label for="email">Email address:</label>
      <input type="email" class="form-control" id="email" required="true">
    </div>
    <div class="form-group">
      <label for="reg">Registration Type:  </label>
      <select class="selectpicker" required="true">
          <option value="1">Self</option>
          <option value="2">Group</option>
          <option value="3">Corporate</option>
          <option value="4">Others</option>
      </select>
    </div>
    <div class= "form-group">
      <label for="noft">Number of Tickets:</label>
      <input type="number" class="form-control" id="noft" ="" max="10" min="1" value = "1" required="true">
    </div>
    <div class="text-center">
      <button type="button" class="btn btn-info" data-toggle="modal" data-target="#myModal">Preview</button>
      <button type="submit" class="btn btn-primary">Submit</button>
    </div>
  </form> -->
  <form method="post" action="" enctype="multipart/form-data">{% csrf_token %}
    <div class="text-center">
      <table>
      {{ form.as_table }}
    </table>
      <button type="button" class="btn btn-info" data-toggle="modal" data-target="#myModal">Preview</button>
      <button type="submit" class="btn btn-primary">Submit</button>
    </div>
  </form>
  {% if messages %}
  <ul class="messages">
      {% for message in messages %}
      <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
      {% endfor %}
  </ul>
  {% endif %}
  </body>
</html>

login/templates/login/success.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Success</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>

    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <!--Selecter dropdown -->
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.1/css/bootstrap-select.min.css">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.1/js/bootstrap-select.min.js"></script>

    <!-- (Optional) Latest compiled and minified JavaScript translation files -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.1/js/i18n/defaults-*.min.js"></script>

    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    {% load static %}

    <link rel="stylesheet" type="text/css" href="{% static 'login/style.css' %}" />
  </head>
  <body class="container">
    <div class = "text-center">
        {% if messages %}
        <ul id="mes">
            {% for message in messages %}
            <li style = "color=blue;">{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}

    <a class="btn btn-primary" href="{% url 'login:index' %}">Home</a>
    </div>
  </body>
</html>

login/templates/login/viewReg.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>AllRegistrations</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>

    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <!--Selecter dropdown -->
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.1/css/bootstrap-select.min.css">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.1/js/bootstrap-select.min.js"></script>

    <!-- (Optional) Latest compiled and minified JavaScript translation files -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.1/js/i18n/defaults-*.min.js"></script>

    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    {% load static %}

    <link rel="stylesheet" type="text/css" href="{% static 'login/style.css' %}" />
  </head>
  <body class="container">
    <table>
      <tr>
        <th>Registration-ID</th>
        <th>Full name</th>
        <th>Mpbile</th>
        <th>Email</th>
        <th>ID</th>
        <th>Type</th>
        <th>No.of.Ticketss</th>
      </tr>
   {% for obj in o_list %}

     <tr>
       <td>{{obj.reg_no}}</td>
       <td>{{obj.name}}</td>
       <td>{{obj.phone_no}}</td>
       <td>{{obj.email}}</td>
       <td>{{obj.id_card}}</td>
       <td>{{obj.reg_type}}</td>
       <td>{{obj.no_of_tkt}}</td>
     </tr>

   {% endfor %}
   </table>
  </body>
</html>